# .scrutinizer.yml
build:

    dependencies:
        before:
            - rm composer.lock

    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'

    nodes:
        # Common versions: 5.4, 5.5, 5.6, 7.1 or hhvm
        php70:
            environment:
                php: 7.0.20

        php71:
            environment:
                php: 7.1

        php72:
            environment:
                php: 7.2

        php56:
            environment:
                php: 5.6

        hhvm:
            environment:
                php: hhvm


checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*


